### ISSUE TITLE
Add Windows Defender configuration tool ConfigureDefender 3.0.0.0 to the list

### ISSUE THREAD

**Issue by SergGu** [alexverboon/MDATP#1]
I think this tool is worth mentioning. It is handy for checking config of single machine

Here is home page - https://github.com/AndyFul/ConfigureDefender
And here is review - https://www.ghacks.net/2020/05/09/windows-defender-configuration-tool-configuredefender-3-0-0-0-released/

**Comment by alexverboon** [comment]
Thanks for your input, added to the list
