### ISSUE TITLE
Add few more microsoft hidden gem links

### ISSUE THREAD

**Issue by SergGu** [alexverboon/MDATP#2]
I checked your great list, and i think below was not listed

- Join Our Security Community (the main hub with a number of truncated links)
https://techcommunity.microsoft.com/t5/security-privacy-compliance/join-our-security-community/m-p/927847

- Security Community Webinars
https://techcommunity.microsoft.com/t5/security-privacy-compliance/security-community-webinars/m-p/927888#M2407

- Become an Azure Sentinel Ninja: The complete level 400 training
https://techcommunity.microsoft.com/t5/azure-sentinel/become-an-azure-sentinel-ninja-the-complete-level-400-training/ba-p/1246310

**Comment by alexverboon** [comment]
Thanks for the input, I have included the above links into the MDATP resouce hub
